package com.example.cryptodrawablesprovider

import android.content.Context
import android.graphics.drawable.Drawable
import android.support.annotation.DrawableRes

/**
 * Created by catalin on 03/04/2018.
 */
fun getCryptoDrawable(cryptoIdentifier: String, context: Context): Drawable {

    @DrawableRes val resId: Int =
            when (cryptoIdentifier) {
                "BTC" -> R.drawable.btc
                "ETH" -> R.drawable.eth
                "XRP" -> R.drawable.xrp
                "BCH" -> R.drawable.bch
                "LTC" -> R.drawable.ltc
                "EOS" -> R.drawable.eos
                "ADA" -> R.drawable.ada
                "XLM" -> R.drawable.xlm
                "NEO" -> R.drawable.neo
                "MIOTA" -> R.drawable.miota
                "XMR" -> R.drawable.xmr
                "DASH" -> R.drawable.dash
                "USDT" -> R.drawable.usdt
                "TRX" -> R.drawable.trx
                "XEM" -> R.drawable.xem
                "BNB" -> R.drawable.bnb
                "ETC" -> R.drawable.etc
                "VEN" -> R.drawable.ven
                "QTUM" -> R.drawable.qtum
                "OMG" -> R.drawable.omg
                "XVG" -> R.drawable.xvg
                "LSK" -> R.drawable.lsk
                "ICX" -> R.drawable.icx
                "BTG" -> R.drawable.btg
                "NANO" -> R.drawable.nano
                "ZEC" -> R.drawable.zec
                "ONT" -> R.drawable.ont
                "STEEM" -> R.drawable.steem
                "PPT" -> R.drawable.ppt
                "BTM" -> R.drawable.btm
                "DGD" -> R.drawable.dgd
                "BCN" -> R.drawable.bcn
                "BTS" -> R.drawable.bts
                "SC" -> R.drawable.sc
                "WAVES" -> R.drawable.waves
                "STRAT" -> R.drawable.strat
                "SNT" -> R.drawable.snt
                "AE" -> R.drawable.ae
                "RHOC" -> R.drawable.rhoc
                "BCD" -> R.drawable.bcd
                "DOGE" -> R.drawable.doge
                "ZRX" -> R.drawable.zrx
                "DCR" -> R.drawable.dcr
                "MKR" -> R.drawable.mkr
                "KMD" -> R.drawable.kmd
                "ZIL" -> R.drawable.zil
                "REP" -> R.drawable.rep
                "ARDR" -> R.drawable.ardr
                "WTC" -> R.drawable.wtc
                "VERI" -> R.drawable.veri
                "AION" -> R.drawable.aion
                "HSR" -> R.drawable.hsr
                "ARK" -> R.drawable.ark
                "PIVX" -> R.drawable.pivx
                "LRC" -> R.drawable.lrc
                "CNX" -> R.drawable.cnx
                "KCS" -> R.drawable.kcs
                "QASH" -> R.drawable.qash
                "IOST" -> R.drawable.iost
                "BAT" -> R.drawable.bat
                "MONA" -> R.drawable.mona
                "DGB" -> R.drawable.dgb
                "FCT" -> R.drawable.fct
                "GNT" -> R.drawable.gnt
                "GAS" -> R.drawable.gas
                "NAS" -> R.drawable.nas
                "ETHOS" -> R.drawable.ethos
                "GXS" -> R.drawable.gxs
                "SYS" -> R.drawable.sys
                "DRGN" -> R.drawable.drgn
                "FUN" -> R.drawable.fun_coin
                "R" -> R.drawable.r
                "ETN" -> R.drawable.etn
                "ELF" -> R.drawable.elf
                "KNC" -> R.drawable.knc
                "XZC" -> R.drawable.xzc
                "SUB" -> R.drawable.sub
                "STORM" -> R.drawable.storm
                "KIN" -> R.drawable.kin
                "RDD" -> R.drawable.rdd
                "NXT" -> R.drawable.nxt
                "POWR" -> R.drawable.powr
                "SALT" -> R.drawable.salt
                "MAID" -> R.drawable.maid
                "DENT" -> R.drawable.dent
                "GBYTE" -> R.drawable.gbyte
                "ENG" -> R.drawable.eng
                "NCASH" -> R.drawable.ncash
                "STORJ" -> R.drawable.storj
                "REQ" -> R.drawable.req
                "WAX" -> R.drawable.wax
                "DCN" -> R.drawable.dcn
                "NEBL" -> R.drawable.nebl
                "BNT" -> R.drawable.bnt
                "SKY" -> R.drawable.sky
                "PAY" -> R.drawable.pay
                "LINK" -> R.drawable.link
                "ACT" -> R.drawable.act
                "EMC" -> R.drawable.emc
                "CND" -> R.drawable.cnd
                "PART" -> R.drawable.part
                "VTC" -> R.drawable.vtc
                "CS" -> R.drawable.cs
                "POLY" -> R.drawable.poly
                "NXS" -> R.drawable.nxs
                "MTL" -> R.drawable.mtl
                "MNX" -> R.drawable.mnx
                "NULS" -> R.drawable.nuls
                "ICN" -> R.drawable.icn
                "ZEN" -> R.drawable.zen
                "ENJ" -> R.drawable.enj
                "CVC" -> R.drawable.cvc
                "MANA" -> R.drawable.mana
                "GVT" -> R.drawable.gvt
                "BLOCK" -> R.drawable.block
                "AUTO" -> R.drawable.auto
                "POA" -> R.drawable.poa
                "RLC" -> R.drawable.rlc
                "GAME" -> R.drawable.game
                "MCO" -> R.drawable.mco
                "GNO" -> R.drawable.gno
                "BTX" -> R.drawable.btx
                "DTR" -> R.drawable.dtr
                "THETA" -> R.drawable.theta
                "QSP" -> R.drawable.qsp
                "BTCD" -> R.drawable.btcd
                "SAN" -> R.drawable.san
                "SMART" -> R.drawable.smart
                "RDN" -> R.drawable.rdn
                "PRL" -> R.drawable.prl
                "ANT" -> R.drawable.ant
                "TNB" -> R.drawable.tnb
                "AGI" -> R.drawable.agi
                "POE" -> R.drawable.poe
                "DBC" -> R.drawable.dbc
                "IGNIS" -> R.drawable.ignis
                "FSN" -> R.drawable.fsn
                "UBQ" -> R.drawable.ubq
                "PPP" -> R.drawable.ppp
                "XDN" -> R.drawable.xdn
                "SRN" -> R.drawable.srn
                "HPB" -> R.drawable.hpb
                "BCO" -> R.drawable.bco
                "NAV" -> R.drawable.nav
                "PLR" -> R.drawable.plr
                "DEW" -> R.drawable.dew
                "ABT" -> R.drawable.abt
                "BOS" -> R.drawable.bos
                "BLZ" -> R.drawable.blz
                "EDO" -> R.drawable.edo
                "GTO" -> R.drawable.gto
                "QRL" -> R.drawable.qrl
                "TEL" -> R.drawable.tel
                "LEND" -> R.drawable.lend
                "BIX" -> R.drawable.bix
                "XAS" -> R.drawable.xas
                "CMT" -> R.drawable.cmt
                "MED" -> R.drawable.med
                "GRS" -> R.drawable.grs
                "ADX" -> R.drawable.adx
                "SLS" -> R.drawable.sls
                "EMC2" -> R.drawable.emc2
                "OST" -> R.drawable.ost
                "XBY" -> R.drawable.xby
                "ION" -> R.drawable.ion
                "EDG" -> R.drawable.edg
                "XP" -> R.drawable.xp
                "RCN" -> R.drawable.rcn
                "FTC" -> R.drawable.ftc
                "DTA" -> R.drawable.dta
                "SPHTX" -> R.drawable.sphtx
                "AMB" -> R.drawable.amb
                "AST" -> R.drawable.ast
                "PURA" -> R.drawable.pura
                "PPC" -> R.drawable.ppc
                "MDS" -> R.drawable.mds
                "RPX" -> R.drawable.rpx
                "ITC" -> R.drawable.itc
                "WPR" -> R.drawable.wpr
                "SNM" -> R.drawable.snm
                "BAY" -> R.drawable.bay
                "SPANK" -> R.drawable.spank
                "NLG" -> R.drawable.nlg
                "UTK" -> R.drawable.utk
                "WINGS" -> R.drawable.wings
                "CRPT" -> R.drawable.crpt
                "QLC" -> R.drawable.qlc
                "VIBE" -> R.drawable.vibe
                "SNGLS" -> R.drawable.sngls
                "DATA" -> R.drawable.data
                "APPC" -> R.drawable.appc
                "MOD" -> R.drawable.mod
                "DNT" -> R.drawable.dnt
                "BRD" -> R.drawable.brd
                "NGC" -> R.drawable.ngc
                "VIA" -> R.drawable.via
                "TNT" -> R.drawable.tnt
                "TAAS" -> R.drawable.taas
                "RVN" -> R.drawable.rvn
                "LBC" -> R.drawable.lbc
                "INS" -> R.drawable.ins
                "WABI" -> R.drawable.wabi
                "WGR" -> R.drawable.wgr
                "XCP" -> R.drawable.xcp
                "BURST" -> R.drawable.burst
                "INK" -> R.drawable.ink
                "JNT" -> R.drawable.jnt
                "FUEL" -> R.drawable.fuel
                "TNC" -> R.drawable.tnc
                "CLOAK" -> R.drawable.cloak
                "BCPT" -> R.drawable.bcpt
                "SBD" -> R.drawable.sbd
                "MLN" -> R.drawable.mln
                "TRIG" -> R.drawable.trig
                "ETP" -> R.drawable.etp
                "HTML" -> R.drawable.html
                "CDT" -> R.drawable.cdt
                "NMC" -> R.drawable.nmc
                "AMP" -> R.drawable.amp
                "VIB" -> R.drawable.vib
                "LUN" -> R.drawable.lun
                "XPA" -> R.drawable.xpa
                "YOYOW" -> R.drawable.yoyow
                "POT" -> R.drawable.pot
                "TKN" -> R.drawable.tkn
                "LKK" -> R.drawable.lkk
                "DAT" -> R.drawable.dat
                "ZCL" -> R.drawable.zcl
                "MTH" -> R.drawable.mth
                "BLK" -> R.drawable.blk
                "EVX" -> R.drawable.evx
                "TIX" -> R.drawable.tix
                "XPM" -> R.drawable.xpm
                "GRC" -> R.drawable.grc
                "VRC" -> R.drawable.vrc
                "DLT" -> R.drawable.dlt
                "MDA" -> R.drawable.mda
                "GUP" -> R.drawable.gup
                "BPT" -> R.drawable.bpt
                "ATM" -> R.drawable.atm
                "NLC2" -> R.drawable.nlc2
                "ARN" -> R.drawable.arn
                "OMNI" -> R.drawable.omni
                "TAU" -> R.drawable.tau
                "OAX" -> R.drawable.oax
                "SLR" -> R.drawable.slr
                "RADS" -> R.drawable.rads
                "XUC" -> R.drawable.xuc
                "EXP" -> R.drawable.exp
                "RISE" -> R.drawable.rise
                "CLAM" -> R.drawable.clam
                "FLO" -> R.drawable.flo
                "NEOS" -> R.drawable.neos
                "XMY" -> R.drawable.xmy
                "CHIPS" -> R.drawable.chips
                "GBX" -> R.drawable.gbx
                "BQ" -> R.drawable.bq
                "MUSIC" -> R.drawable.music
                "FLDC" -> R.drawable.fldc
                "CTR" -> R.drawable.ctr
                "ARY" -> R.drawable.ary
                "PIRL" -> R.drawable.pirl
                "PINK" -> R.drawable.pink
                "BCC" -> R.drawable.bcc
                "IOP" -> R.drawable.iop
                "BNTY" -> R.drawable.bnty
                "ELIX" -> R.drawable.elix
                "BTCZ" -> R.drawable.btcz
                "BELA" -> R.drawable.bela
                "RIC" -> R.drawable.ric
                "XBC" -> R.drawable.xbc
                "HUSH" -> R.drawable.hush
                "KRB" -> R.drawable.krb
                "CRED" -> R.drawable.cred
                "EBST" -> R.drawable.ebst
                "TZC" -> R.drawable.tzc
                "HUC" -> R.drawable.huc
                "MCAP" -> R.drawable.mcap
                "XMG" -> R.drawable.xmg
                "ELLA" -> R.drawable.ella
                "MZC" -> R.drawable.mzc
                "VIVO" -> R.drawable.vivo
                "START" -> R.drawable.start
                "BDL" -> R.drawable.bdl
                "COB" -> R.drawable.cob
                "FAIR" -> R.drawable.fair
                "XVC" -> R.drawable.xvc
                "CDN" -> R.drawable.cdn
                "PASL" -> R.drawable.pasl
                "XTZ" -> R.drawable.xtz
                "BTCP" -> R.drawable.btcp
                "FIL" -> R.drawable.fil
                "PAC" -> R.drawable.pac
                "UNITY" -> R.drawable.unity
                "OX" -> R.drawable.ox
                else -> R.drawable.ic_error_black_24dp
            }
    return context.getDrawable(resId)
}