package com.catalinj.cryptosmart.datalayer

enum class CurrencyRepresentation(val currency: String) {
    AUD(currency = "AUD"),
    BRL(currency = "BRL"),
    BTC(currency = "BTC"),
    CAD(currency = "CAD"),
    CHF(currency = "CHF"),
    CLP(currency = "CLP"),
    CNY(currency = "CNY"),
    CZK(currency = "CZK"),
    DKK(currency = "DKK"),
    EUR(currency = "EUR"),
    GBP(currency = "GBP"),
    HKD(currency = "HKD"),
    HUF(currency = "HUF"),
    IDR(currency = "IDR"),
    ILS(currency = "ILS"),
    INR(currency = "INR"),
    JPY(currency = "JPY"),
    KRW(currency = "KRW"),
    MXN(currency = "MXN"),
    MYR(currency = "MYR"),
    NOK(currency = "NOK"),
    NZD(currency = "NZD"),
    PHP(currency = "PHP"),
    PKR(currency = "PKR"),
    PLN(currency = "PLN"),
    RUB(currency = "RUB"),
    SEK(currency = "SEK"),
    SGD(currency = "SGD"),
    THB(currency = "THB"),
    USD(currency = "USD"),
    TRY(currency = "TRY"),
    TWD(currency = "TWD"),
    ZAR(currency = "ZAR")
}